name: app_night_street
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  logger: ^2.0.1
  get: 4.6.6
  flutter_svg: ^2.0.9

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/svg/

  fonts:
    - family: Montserrat-Arabic
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
